[package]
name = "tmg"
version = "0.1.0"
authors = ["Exiam <exiam@pm.me>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
chrono = "0.4.7"
tui = "0.9"
termion = "1.5"
structopt = "0.3.9"
rand = "0.7"
