.PHONY: install help
.DEFAULT_GOAL := help

install:
	cp target/release/rust /usr/local/bin/tmg

help:
	@echo " ______ __   __  ____  "
	@echo "|______|  \_/  |/ ___| "
	@echo "  |  | | |\_/| | |  _  "
	@echo "  |  | | |   | | |_| | "
	@echo "  |__| |_|   |_|\____| "
	@echo "                       "
	@echo "====== Makefile =======\n"
	@echo "install: Install tmg for local user\n"